PUBLICATIONS = [
    {
        "source_key": "Gu2023",
        "first_author_last": "Gu",
        "all_authors": r"Gu, Yuhua and Song, Shuaijie and Zhu, Qingrui and Jiao, Ruilin and Lin, Xu'ai and Yang, Fan and van der Veen, Stijn",
        "year": 2023,
        "doi": "10.1128/spectrum.02449-23",
        "url": "https://journals.asm.org/doi/10.1128/spectrum.02449-23",
        "abstract": None,
        "is_open_access": True,
        "data_available": False,
        "license": "CC-BY-4.0",
        "notes": "",
        "citation_bibtex": r"@article{gu2023bacitracin, title={Bacitracin enhances ceftriaxone susceptibility of the high-level ceftriaxone-resistant gonococcal FC428 clone}, author={Gu, Yuhua and Song, Shuaijie and Zhu, Qingrui and Jiao, Ruilin and Lin, Xu'ai and Yang, Fan and van der Veen, Stijn}, journal={Microbiology Spectrum}, volume={11}, number={6}, pages={e02449--23}, year={2023}, publisher={American Society for Microbiology 1752 N St., NW, Washington, DC}}",
    },
    {
        "source_key": "Hauser2015",
        "first_author_last": "Hauser",
        "all_authors": r"Hauser, Christoph and Hirzberger, Lea and Unemo, Magnus and Furrer, Hansjakob and Endimiani, Andrea",
        "year": 2015,
        "doi": "10.1128/aac.04536-14",
        "url": "https://journals.asm.org/doi/10.1128/aac.04536-14",
        "abstract": None,
        "is_open_access": False,
        "data_available": False,
        "license": "Copyright (c) 2015, American Society for Microbiology. All Rights Reserved.",
        "notes": "",
        "citation_bibtex": r"@article{hauser2015vitro, title={In vitro activity of fosfomycin alone and in combination with ceftriaxone or azithromycin against clinical Neisseria gonorrhoeae isolates}, author={Hauser, Christoph and Hirzberger, Lea and Unemo, Magnus and Furrer, Hansjakob and Endimiani, Andrea}, journal={Antimicrobial agents and chemotherapy}, volume={59}, number={3}, pages={1605--1611}, year={2015}, publisher={American Society for Microbiology 1752 N St., NW, Washington, DC}}",
    },
    {
        "source_key": "Gubensek2022",
        "first_author_last": "Gubensek",
        "all_authors": r"Guben{\v{s}}ek, Ur{\v{s}}a and de Laat, Myrthe and Foerster, Sunniva and Boyd, Anders and van Dam, Alje Pieter",
        "year": 2022,
        "doi": "10.3390/antibiotics11030299",
        "url": "https://www.mdpi.com/2079-6382/11/3/299",
        "abstract": None,
        "is_open_access": True,
        "data_available": True,
        "license": "CC-BY-4.0",
        "notes": "",
        "citation_bibtex": r"@article{gubenvsek2022pharmacodynamics, title={Pharmacodynamics of ceftriaxone, ertapenem, fosfomycin and gentamicin in Neisseria gonorrhoeae}, author={Guben{\v{s}}ek, Ur{\v{s}}a and de Laat, Myrthe and Foerster, Sunniva and Boyd, Anders and van Dam, Alje Pieter}, journal={Antibiotics}, volume={11}, number={3}, pages={299}, year={2022}, publisher={MDPI}}",
    },
    {
        "source_key": "Chisholm2010",
        "first_author_last": "Chisholm",
        "all_authors": r"Chisholm, Stephanie A and Mouton, Johan W and Lewis, David A and Nichols, Tom and Ison, Catherine A and Livermore, David M",
        "year": 2010,
        "doi": "10.1093/jac/dkq289",
        "url": "https://academic.oup.com/jac/article-abstract/65/10/2141/706206?redirectedFrom=fulltext",
        "abstract": None,
        "is_open_access": False,
        "data_available": False,
        "license": "(c) The Author 2010. Published by Oxford University Press on behalf of the British Society for Antimicrobial Chemotherapy. All rights reserved.",
        "notes": "",
        "citation_bibtex": r"@article{chisholm2010cephalosporin, title={Cephalosporin MIC creep among gonococci: time for a pharmacodynamic rethink?}, author={Chisholm, Stephanie A and Mouton, Johan W and Lewis, David A and Nichols, Tom and Ison, Catherine A and Livermore, David M}, journal={Journal of antimicrobial chemotherapy}, volume={65}, number={10}, pages={2141--2148}, year={2010}, publisher={Oxford University Press}}",
    },
    {
        "source_key": "Foerster2015",
        "first_author_last": "Foerster",
        "all_authors": r"Foerster, Sunniva and Golparian, Daniel and Jacobsson, Susanne and Hathaway, Lucy J and Low, Nicola and Shafer, William M and Althaus, Christian L and Unemo, Magnus",
        "year": 2015,
        "doi": "10.3389/fmicb.2015.01377",
        "url": "https://www.frontiersin.org/journals/microbiology/articles/10.3389/fmicb.2015.01377/full",
        "abstract": None,
        "is_open_access": True,
        "data_available": True,
        "license": "CC-BY-4.0",
        "notes": "",
        "citation_bibtex": r"@article{foerster2015genetic, title={Genetic resistance determinants, in vitro time-kill curve analysis and pharmacodynamic functions for the novel topoisomerase II inhibitor ETX0914 (AZD0914) in Neisseria gonorrhoeae}, author={Foerster, Sunniva and Golparian, Daniel and Jacobsson, Susanne and Hathaway, Lucy J and Low, Nicola and Shafer, William M and Althaus, Christian L and Unemo, Magnus}, journal={Frontiers in microbiology}, volume={6}, pages={1377}, year={2015}, publisher={Frontiers Media SA}}",
    },
    {
        "source_key": "Foerster2016",
        "first_author_last": "Foerster",
        "all_authors": r"Foerster, Sunniva and Unemo, Magnus and Hathaway, Lucy J and Low, Nicola and Althaus, Christian L",
        "year": 2016,
        "doi": "10.1186/s12866-016-0838-9",
        "url": "https://link.springer.com/article/10.1186/s12866-016-0838-9",
        "abstract": None,
        "is_open_access": True,
        "data_available": True,
        "license": "CC-BY-4.0",
        "notes": "",
        "citation_bibtex": r"@article{foerster2016time, title={Time-kill curve analysis and pharmacodynamic modelling for in vitro evaluation of antimicrobials against Neisseria gonorrhoeae}, author={Foerster, Sunniva and Unemo, Magnus and Hathaway, Lucy J and Low, Nicola and Althaus, Christian L}, journal={BMC microbiology}, volume={16}, number={1}, pages={216}, year={2016}, publisher={Springer}}",
    },
    {
        "source_key": "Unemo2024",
        "first_author_last": "Unemo",
        "all_authors": r"Unemo, Magnus and Golparian, Daniel and Oxelbark, Joakim and Kong, Fabian YS and Brown, David and Louie, Arnold and Drusano, George and Jacobsson, Susanne",
        "year": 2024,
        "doi": "10.1093/jac/dkae063 ",
        "url": "https://academic.oup.com/jac/article/79/5/1006/7630705",
        "abstract": None,
        "is_open_access": False,
        "data_available": True,
        "license": "(c) The Author(s) 2024. Published by Oxford University Press on behalf of British Society for Antimicrobial Chemotherapy. All rights reserved.",
        "notes": "Free but not open access.",
        "citation_bibtex": r"@article{unemo2024pharmacodynamic, title={Pharmacodynamic evaluation of ceftriaxone single-dose therapy (0.125--1 g) to eradicate ceftriaxone-susceptible and ceftriaxone-resistant Neisseria gonorrhoeae strains in a hollow fibre infection model for gonorrhoea}, author={Unemo, Magnus and Golparian, Daniel and Oxelbark, Joakim and Kong, Fabian YS and Brown, David and Louie, Arnold and Drusano, George and Jacobsson, Susanne}, journal={Journal of Antimicrobial Chemotherapy}, volume={79}, number={5}, pages={1006--1013}, year={2024}, publisher={Oxford University Press UK}}",
    },
]
